"""
Phase AS: quantitative cluster-binding benchmark from the feedback ODE
======================================================================

Goal:
  Replace the purely verbal cluster argument with a minimal quantitative
  benchmark for the extra binding generated by resonant-tail accumulation.

Model:
  1. Use the quantum feedback ODE normalization at z = 0:

         eps_dot(0) = 3 H0 rho_DE,0 delta_w0 .

  2. Build a local cluster excess energy density eps_cl(t) with leakage:

         d eps_cl / dt
           = S0 * delta_cl(z) * (1+z)^3 * e^{2phi_bg(z)-2phi_bg(0)}
             - eps_cl / tau_ret .

  3. Integrate from z = 2 to z = 0 for two density histories:
       - constant overdensity:      delta_cl(z) = delta_cl,0
       - constant physical density: delta_cl(z) = delta_cl,0 / (1+z)^3

  4. Compare the resulting extra effective density

         rho_extra = eps_cl / c^2

     to the mean cluster baryon density rho_cl.

Key question:
  Does the residual cluster gap remain tiny (ballistic escape, tau_ret = R/c),
  or can it reach O(50%) if the background is retained on the cluster
  turnover time tau_ret ~ R / v_turb ?
"""

from pathlib import Path
import io
import sys

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")


sys.path.insert(0, str(Path(__file__).parent))

from constants import G, Gyr, H0, Msun, c, kpc
from phi_evolution import H_of_z, coupling_ratio
from multiscale import dw0_from_master_formula


SEP = "=" * 78
OUTDIR = Path(__file__).parent / "plots"
OUTDIR.mkdir(exist_ok=True)
PDF_DIR = Path(__file__).parent.parent / "PDF"
PDF_DIR.mkdir(exist_ok=True)

RHO_DE0 = 6.0e-10          # J / m^3
OMEGA_B = 0.05
ALPHA_Q = 1.0
Z_CLUSTER_FORM = 2.0
Z_QUANTUM_FORM = 10.0
K_MASTER = 8.0
DW0_FID = dw0_from_master_formula(Z_QUANTUM_FORM, ALPHA_Q, K_MASTER)

M_CLUSTER = 1.0e14 * Msun
R_CLUSTER = 1.0e3 * kpc
V_TURNOVER_FAST = 1.0e6    # 1000 km/s
V_TURNOVER_VIR = 6.5e5     # 650 km/s


def cluster_case():
    volume = 4.0 * np.pi * R_CLUSTER**3 / 3.0
    rho_cl = M_CLUSTER / volume
    rho_crit0 = 3.0 * H0**2 / (8.0 * np.pi * G)
    delta0 = rho_cl / (OMEGA_B * rho_crit0)
    tau_esc = R_CLUSTER / c
    v_vir = np.sqrt(G * M_CLUSTER / R_CLUSTER)
    return {
        "M": M_CLUSTER,
        "R": R_CLUSTER,
        "rho_cl": rho_cl,
        "delta0": delta0,
        "tau_esc": tau_esc,
        "v_vir": v_vir,
    }


def source_rate_today(dw0):
    return 3.0 * H0 * RHO_DE0 * dw0


def z_grid_with_timesteps(z_form=Z_CLUSTER_FORM, n_steps=5000):
    z = np.linspace(z_form, 0.0, n_steps)
    z_mid = 0.5 * (z[:-1] + z[1:])
    dtdz = 1.0 / ((1.0 + z) * H_of_z(z))
    dt = np.abs(0.5 * (dtdz[:-1] + dtdz[1:]) * np.diff(z))
    return z, z_mid, dt


def density_history(z, delta0, mode):
    z = np.asarray(z, dtype=float)
    if mode == "const_overdensity":
        return np.full_like(z, delta0)
    if mode == "const_physical":
        return delta0 / (1.0 + z) ** 3
    raise ValueError(f"Unknown density-history mode: {mode}")


def source_history(z, alpha=ALPHA_Q, dw0=DW0_FID, mode="quantum"):
    z = np.asarray(z, dtype=float)
    if mode == "present":
        return np.ones_like(z)
    if mode == "quantum":
        return (1.0 + z) ** 3 * coupling_ratio(z, alpha, dw0)
    raise ValueError(f"Unknown source-history mode: {mode}")


def integrate_cluster_excess(case, tau_ret, density_mode,
                             z_form=Z_CLUSTER_FORM,
                             alpha=ALPHA_Q, dw0=DW0_FID,
                             source_mode="quantum"):
    _, z_mid, dt = z_grid_with_timesteps(z_form=z_form)
    delta_hist = density_history(z_mid, case["delta0"], density_mode)
    source_hist = source_history(z_mid, alpha=alpha, dw0=dw0, mode=source_mode)

    eps_scaled = 0.0
    for src_ratio, delta_here, dt_here in zip(source_hist, delta_hist, dt):
        source_here = delta_here * src_ratio
        decay = np.exp(-dt_here / tau_ret)
        eps_scaled = eps_scaled * decay + source_here * tau_ret * (1.0 - decay)

    eps_loc = eps_scaled * source_rate_today(dw0)
    return {
        "eps_loc": eps_loc,
        "rho_extra": eps_loc / c**2,
        "binding_fraction": eps_loc / (c**2 * case["rho_cl"]),
        "f_eff_total": eps_loc / RHO_DE0,
    }


def trap_factor_from_tau(case, tau_ret):
    return tau_ret / case["tau_esc"]


def tau_from_velocity(case, v):
    return case["R"] / v


def trap_grid_scan(case, density_mode, dw0=DW0_FID):
    trap_grid = np.geomspace(1.0, 1.0e3, 220)
    frac_present = []
    frac_quantum = []

    for trap in trap_grid:
        tau_ret = case["tau_esc"] * trap
        frac_present.append(
            integrate_cluster_excess(
                case, tau_ret, density_mode, dw0=dw0, source_mode="present"
            )["binding_fraction"]
        )
        frac_quantum.append(
            integrate_cluster_excess(
                case, tau_ret, density_mode, dw0=dw0, source_mode="quantum"
            )["binding_fraction"]
        )

    return {
        "trap": trap_grid,
        "present": np.asarray(frac_present),
        "quantum": np.asarray(frac_quantum),
    }


def dw0_scan(case, density_mode, tau_ret):
    dw0_grid = np.linspace(0.02, 0.30, 120)
    frac_grid = []
    for dw0 in dw0_grid:
        frac_grid.append(
            integrate_cluster_excess(
                case, tau_ret, density_mode, dw0=dw0, source_mode="quantum"
            )["binding_fraction"]
        )
    return {"dw0": dw0_grid, "fraction": np.asarray(frac_grid)}


def required_trap_for_fraction(case, density_mode, target_fraction=0.5):
    scan = trap_grid_scan(case, density_mode, dw0=DW0_FID)
    frac = scan["quantum"]
    trap = scan["trap"]
    if np.all(frac < target_fraction):
        return np.nan
    return float(np.interp(target_fraction, frac, trap))


def sample_table(case, density_mode, traps, dw0=DW0_FID):
    rows = []
    for trap in traps:
        tau_ret = case["tau_esc"] * trap
        present = integrate_cluster_excess(
            case, tau_ret, density_mode, dw0=dw0, source_mode="present"
        )
        quantum = integrate_cluster_excess(
            case, tau_ret, density_mode, dw0=dw0, source_mode="quantum"
        )
        rows.append({
            "trap": trap,
            "tau_gyr": tau_ret / Gyr,
            "present": present["binding_fraction"],
            "quantum": quantum["binding_fraction"],
            "history_factor": quantum["binding_fraction"] / max(present["binding_fraction"], 1e-300),
            "f_eff_total": quantum["f_eff_total"],
        })
    return rows


def make_plots(case, trap_scans, dw0_scans):
    fig, axes = plt.subplots(1, 2, figsize=(13.5, 5.2))

    ax = axes[0]
    for label, scan in trap_scans.items():
        pretty = "constant overdensity" if label == "const_overdensity" else "constant physical density"
        ax.loglog(scan["trap"], scan["present"], ls="--", lw=1.8, label=f"{pretty}, present-rate")
        ax.loglog(scan["trap"], scan["quantum"], lw=2.3, label=f"{pretty}, quantum history")
    ax.axhline(0.5, color="k", ls=":", lw=1.4, label=r"target $\rho_{\rm extra}/\rho_{\rm cl}=0.5$")
    ax.axvline(c / V_TURNOVER_FAST, color="gray", ls="-.", lw=1.4, label=r"$\tau_{\rm ret}=R/(1000\,{\rm km\,s^{-1}})$")
    ax.axvline(c / V_TURNOVER_VIR, color="dimgray", ls=":", lw=1.6, label=r"$\tau_{\rm ret}=R/(650\,{\rm km\,s^{-1}})$")
    ax.set_xlabel(r"retention factor $\tau_{\rm ret}/\tau_{\rm esc}$")
    ax.set_ylabel(r"extra binding fraction $\rho_{\rm extra}/\rho_{\rm cl}$")
    ax.set_title("(a) Cluster binding vs retention")
    ax.legend(fontsize=8)

    ax = axes[1]
    for label, scan in dw0_scans.items():
        pretty = "constant overdensity" if label == "const_overdensity" else "constant physical density"
        ax.plot(scan["dw0"], scan["fraction"], lw=2.3, label=pretty)
    ax.axhline(0.5, color="k", ls=":", lw=1.4)
    ax.axvline(DW0_FID, color="gray", ls="--", lw=1.5, label=rf"fiducial $\delta w_0={DW0_FID:.3f}$")
    ax.set_xlabel(r"$\delta w_0$")
    ax.set_ylabel(r"$\rho_{\rm extra}/\rho_{\rm cl}$ at $\tau_{\rm ret}=R/(1000\,{\rm km\,s^{-1}})$")
    ax.set_title("(b) EOS sensitivity at turnover retention")
    ax.legend(fontsize=8)

    fig.suptitle("Phase AS: Cluster Binding from the Feedback ODE", y=0.99)
    fig.tight_layout()

    outpath = OUTDIR / "phase_as_cluster_binding.png"
    pdf_path = PDF_DIR / "fig_mond_cluster_binding.pdf"
    fig.savefig(outpath, dpi=180, bbox_inches="tight")
    fig.savefig(pdf_path, bbox_inches="tight")
    plt.close(fig)
    return outpath


def print_results(case, trap_scans):
    print(SEP)
    print("  PHASE AS: Cluster Binding from the Feedback ODE")
    print(SEP)
    print("  Fiducial rich cluster:")
    print(f"    M_bary = {case['M']/Msun:.2e} Msun")
    print(f"    R      = {case['R']/(1.0e3*kpc):.2f} Mpc")
    print(f"    rho_cl = {case['rho_cl']:.3e} kg/m^3")
    print(f"    delta0 = rho_cl / (Omega_b rho_crit,0) = {case['delta0']:.2f}")
    print(f"    tau_esc = R/c = {case['tau_esc']/Gyr:.4f} Gyr")
    print()
    print("  Quantum inputs:")
    print(f"    cluster history window   : z = {Z_CLUSTER_FORM:.0f} -> 0")
    print(f"    feedback exponent alpha  : {ALPHA_Q:.1f}")
    print(f"    fiducial delta_w0        : {DW0_FID:.4f}  (from K ~= {K_MASTER:.1f}, z_f = {Z_QUANTUM_FORM:.0f})")
    print()

    trap_samples = [1, 10, 30, 100, 300, 500]
    for mode in ("const_overdensity", "const_physical"):
        pretty = "constant overdensity" if mode == "const_overdensity" else "constant physical density"
        rows = sample_table(case, mode, trap_samples)
        trap50 = required_trap_for_fraction(case, mode, target_fraction=0.5)
        v_req = c / trap50 if np.isfinite(trap50) else np.nan
        tau_req = case["tau_esc"] * trap50 if np.isfinite(trap50) else np.nan

        print(f"  Density history: {pretty}")
        print("    trap     tau_ret[Gyr]   frac[present]   frac[quantum]   history factor")
        for row in rows:
            print(
                f"    {row['trap']:4.0f}      {row['tau_gyr']:10.4f}"
                f"      {row['present']:12.4f}   {row['quantum']:12.4f}"
                f"      {row['history_factor']:8.3f}"
            )
        print(
            f"    target 50% reached at trap ~= {trap50:.1f}, "
            f"tau_ret ~= {tau_req/Gyr:.3f} Gyr, "
            f"v_eff ~= {v_req/1e3:.0f} km/s"
        )
        print()

    tau_turn_fast = tau_from_velocity(case, V_TURNOVER_FAST)
    tau_turn_vir = tau_from_velocity(case, V_TURNOVER_VIR)
    print("  Turnover-time retention benchmarks:")
    print(
        f"    v_turb = 1000 km/s -> tau_ret = {tau_turn_fast/Gyr:.3f} Gyr, "
        f"trap = {trap_factor_from_tau(case, tau_turn_fast):.1f}"
    )
    print(
        f"    v_turb =  650 km/s -> tau_ret = {tau_turn_vir/Gyr:.3f} Gyr, "
        f"trap = {trap_factor_from_tau(case, tau_turn_vir):.1f}"
    )
    print()

    print("  delta_w0 sensitivity at tau_ret = R/(1000 km/s):")
    for dw0 in [0.05, 0.10, DW0_FID, 0.30]:
        frac = integrate_cluster_excess(
            case, tau_turn_fast, "const_physical", dw0=dw0, source_mode="quantum"
        )["binding_fraction"]
        print(f"    delta_w0 = {dw0:7.4f} -> rho_extra/rho_cl = {frac:7.4f}")
    print()

    ballistic = integrate_cluster_excess(
        case, case["tau_esc"], "const_physical", dw0=DW0_FID, source_mode="quantum"
    )["binding_fraction"]
    turnover = integrate_cluster_excess(
        case, tau_turn_fast, "const_physical", dw0=DW0_FID, source_mode="quantum"
    )["binding_fraction"]
    print("  Reading:")
    print(
        "  - ballistic escape (tau_ret = R/c) reproduces the old lower bound:"
        f" rho_extra/rho_cl ~= {ballistic:.4f};"
    )
    print(
        "  - for a late cluster history (z <= 2), the quantum source history adds"
        " only a modest O(1.01-1.12) correction;"
    )
    print(
        "  - the dominant lever is therefore retention, not the early-epoch source"
        " enhancement by itself;"
    )
    print(
        "  - if tau_ret is set by a turnover time R/v_turb rather than a ballistic"
        f" light-crossing time, the fiducial benchmark rises to rho_extra/rho_cl ~= {turnover:.4f}"
        " already for v_turb = 1000 km/s;"
    )
    print(
        "  - so the cluster residual can be quantitatively closed provided the"
        " long-wavelength tail background is retained on the cluster flow time;"
    )
    print(
        "  - if escape remains ballistic, the cluster gap stays open."
    )
    print(SEP)


def main():
    case = cluster_case()

    trap_scans = {
        "const_overdensity": trap_grid_scan(case, "const_overdensity"),
        "const_physical": trap_grid_scan(case, "const_physical"),
    }

    tau_turn_fast = tau_from_velocity(case, V_TURNOVER_FAST)
    dw0_scans = {
        "const_overdensity": dw0_scan(case, "const_overdensity", tau_turn_fast),
        "const_physical": dw0_scan(case, "const_physical", tau_turn_fast),
    }

    plot_path = make_plots(case, trap_scans, dw0_scans)
    print_results(case, trap_scans)
    print(f"  Plot saved to: {plot_path}")


if __name__ == "__main__":
    main()
